[package]
name = "wirm"
version = "4.0.0-rc3"
edition = "2021"
authors = ["Suhas Thalanki", "Alex Bai", "Elizabeth Gilbert"]
description = "A lightweight WebAssembly Transformation Library for the Component Model"
readme = "README.md"
homepage = "https://github.com/composablesys/wirm"
repository = "https://github.com/composablesys/wirm"
license = "Apache-2.0"
categories = ["wasm"]
keywords = ["wasm", "WebAssembly", "instrumentation"]
include = ["src/**/*.rs", "Cargo.toml"]

[dependencies]
log = "0.4.22"
paste = "1"
rayon = { version = "1.8", optional = true }
wasm-encoder = { version = "0.245.0", features = ["wasmparser"] }
wasmparser = "0.245.0"

[dev-dependencies]
wast = "245.0.0"
wasmprinter = "0.245.0"
wat = "1.245.0"
wasmtime = "40.0.0"

[features]
default = []
## Enable parallel processing during module parsing and encoding using rayon.
parallel = ["rayon"]
