use std::collections::{BTreeMap, HashMap};

use crate::error::Error;
use crate::ir::types::CustomSection;

/// Wasm DWARF uses 32-bit code addresses.
const WASM_DWARF_ADDRESS_SIZE: u8 = 4;
/// Byte length of the unit-length field at the start of a DWARF32 line program.
const DWARF32_LENGTH_FIELD_BYTES: usize = 4;
/// Byte length of the unit-length field at the start of a DWARF64 line program
/// (4-byte 0xffffffff magic + 8-byte length).
const DWARF64_LENGTH_FIELD_BYTES: usize = 12;

/// Per-function input-side metadata the DWARF rewriter consults to translate
/// in-function PCs to/from DWARF row addresses.
///
/// Assumes inputs generated by `wasm-tools parse --generate-dwarf`, whose
/// addresses are module-cumulative: each function's DWARF address space picks
/// up where the previous function's body ended. `dwarf_addr_base` records that
/// per-function base offset; the legacy "per-function spaces start at 0"
/// case is its degenerate single-function form.
#[derive(Clone, Debug)]
pub struct OrigFuncDebugData {
    /// Module-cumulative DWARF address of the function's first body byte (the
    /// size LEB). Equals the sum of preceding local functions'
    /// `body_total_size`, computed at parse time so the rewriter can route
    /// CU-level addresses to the right function.
    pub dwarf_addr_base: usize,
    /// Byte length of the function-body size LEB. The body-content start (just
    /// past the size LEB) sits `dwarf_addr_base + size_leb_len` bytes in —
    /// wasm-tools' typical `subprogram` `low_pc` lands here.
    pub size_leb_len: usize,
    /// In-function DWARF offset of the first instruction (= size LEB bytes +
    /// locals-declaration bytes, counted from the body's size LEB byte). Add
    /// `dwarf_addr_base` for the absolute module address.
    pub first_instr_dwarf_offset: usize,
    /// Total bytes of the function body including the size LEB. The function
    /// occupies module-cumulative addresses
    /// `[dwarf_addr_base, dwarf_addr_base + body_total_size)`.
    pub body_total_size: usize,
}

#[derive(Clone, Debug, Default)]
pub struct ModuleDebugData<'a> {
    /// `.debug_*` sections in the order they appeared in the input module.
    /// Encode emits them in this order after the rest of `custom_sections`.
    pub(crate) sections: Vec<CustomSection<'a>>,
    /// Per-local-function metadata, keyed by function index.
    pub(crate) per_func: HashMap<u32, OrigFuncDebugData>,
}

impl<'a> ModuleDebugData<'a> {
    pub(crate) fn new(
        sections: Vec<CustomSection<'a>>,
        per_func: HashMap<u32, OrigFuncDebugData>,
    ) -> Self {
        Self { sections, per_func }
    }

    /// Read-only view of the underlying `.debug_*` custom sections.
    pub fn sections(&self) -> &[CustomSection<'a>] {
        &self.sections
    }

    /// Whether a custom-section name matches the DWARF convention. Includes
    /// any `.debug_*` name so non-standard extensions still round-trip via
    /// `ModuleDebugData` rather than escaping into `custom_sections`.
    pub fn is_dwarf_section_name(name: &str) -> bool {
        name.starts_with(".debug_")
    }
}

/// Walk per-function entries in code-section order and stamp each entry's
/// `dwarf_addr_base` to the running sum of preceding `body_total_size`s.
/// Callers vary in storage type (parse side: `usize`, encode side:
/// `Option<usize>`), so the setter is a closure.
pub(crate) fn assign_cumulative_dwarf_addr_bases<T>(
    entries: impl IntoIterator<Item = T>,
    body_size: impl Fn(&T) -> usize,
    mut set_base: impl FnMut(T, usize),
) {
    let mut cumulative = 0usize;
    for entry in entries {
        let size = body_size(&entry);
        set_base(entry, cumulative);
        cumulative += size;
    }
}

/// New per-function maps the rewriter consults to emit translated DWARF rows.
pub(crate) struct PerFuncEncodeMaps<'m> {
    /// Start byte of each emitted op within the function body, emit order.
    pub pcs: &'m [usize],
    /// Original-instruction index each emitted op anchors to.
    pub anchors: &'m [usize],
    /// For each orig op index, the emit position of the orig op itself (vs
    /// `anchors.position(|a| a == idx)`, which would point at a leading
    /// before-injection). When the orig op is replaced by an alt, this is
    /// the first emit position in the alt sequence.
    pub self_emit_for_orig: &'m [usize],
    /// Module-cumulative DWARF address of this function's first body byte in
    /// the *new* module — sum of preceding new functions' `body_total_size`.
    pub dwarf_addr_base: usize,
    /// Byte length of the new function-body size LEB.
    pub size_leb_len: usize,
    /// In-function DWARF offset of the first instruction in the new module
    /// body. Add `dwarf_addr_base` for the absolute address.
    pub first_instr_dwarf_offset: usize,
    /// Total bytes of the new function body (size LEB + content).
    pub body_total_size: usize,
}

/// Rewrite `.debug_line` so row addresses match the new code layout. Each row
/// inherits the source location of the original op its emitted op anchors to.
/// Assumes one sequence per local function in code-section order
/// (`wasm-tools parse --generate-dwarf`'s convention).
pub(crate) fn rewrite_debug_line(
    input_bytes: &[u8],
    debug: &ModuleDebugData,
    per_func_new: &BTreeMap<u32, PerFuncEncodeMaps<'_>>,
    orig_per_instr_pcs: &BTreeMap<u32, &[usize]>,
) -> Result<Vec<u8>, Error> {
    use gimli::{
        write::{self, Address, ConvertLineRow, DebugLine, EndianVec},
        EndianSlice, LittleEndian, SectionId,
    };

    let endian = LittleEndian;
    let dl_bytes = EndianSlice::new(input_bytes, endian);
    let empty = EndianSlice::new(&[], endian);

    let section_lookup = |name: &str| -> Option<EndianSlice<'_, LittleEndian>> {
        debug
            .sections()
            .iter()
            .find(|s| s.name == name)
            .map(|s| EndianSlice::new(s.data.as_ref(), endian))
    };
    let debug_str_bytes = section_lookup(".debug_str").unwrap_or(empty);
    let debug_line_str_bytes = section_lookup(".debug_line_str").unwrap_or(empty);
    let debug_str_offsets_bytes = section_lookup(".debug_str_offsets").unwrap_or(empty);

    let dwarf_read = gimli::read::Dwarf::load(|id| -> Result<_, gimli::Error> {
        Ok(match id {
            SectionId::DebugLine => dl_bytes,
            SectionId::DebugStr => debug_str_bytes,
            SectionId::DebugLineStr => debug_line_str_bytes,
            SectionId::DebugStrOffsets => debug_str_offsets_bytes,
            _ => empty,
        })
    })
    .map_err(|e| Error::DwarfError(format!("loading .debug_line: {e}")))?;

    // Parse the line program at offset 0. Multi-program (multi-CU) inputs are
    // refused below; the rewriter doesn't yet route per-CU.
    let from_program = dwarf_read
        .debug_line
        .program(
            gimli::DebugLineOffset(0),
            WASM_DWARF_ADDRESS_SIZE,
            None,
            None,
        )
        .map_err(|e| Error::DwarfError(format!("opening line program: {e}")))?;

    let header = from_program.header();
    let length_field_size = match header.encoding().format {
        gimli::Format::Dwarf32 => DWARF32_LENGTH_FIELD_BYTES,
        gimli::Format::Dwarf64 => DWARF64_LENGTH_FIELD_BYTES,
    };
    let first_program_bytes = length_field_size + header.unit_length();
    if first_program_bytes < input_bytes.len() {
        return Err(Error::DwarfError(format!(
            "multi-program .debug_line not yet supported ({first_program_bytes}/{} bytes consumed by the first program)",
            input_bytes.len()
        )));
    }

    let mut dwarf_write = write::Dwarf::new();
    let mut convert = dwarf_write
        .read_line_program(&dwarf_read, from_program, None, None)
        .map_err(|e| Error::DwarfError(format!("converter init: {e}")))?;

    // Walk input rows, grouping into sequences. We capture each row's
    // absolute address so we can rebuild the orig_pc → row lookup per
    // function below.
    struct CollectedRow {
        address: u64,
        row: write::LineRow,
    }
    let mut sequences: Vec<Vec<CollectedRow>> = Vec::new();
    let mut current_sequence: Vec<CollectedRow> = Vec::new();
    let mut current_base: u64 = 0;
    loop {
        let item = convert
            .read_row()
            .map_err(|e| Error::DwarfError(format!("reading row: {e}")))?;
        let Some(item) = item else {
            break;
        };
        match item {
            ConvertLineRow::SetAddress(addr) => {
                current_base = addr;
            }
            ConvertLineRow::Row(row) => {
                let address = current_base + row.address_offset;
                current_sequence.push(CollectedRow { address, row });
            }
            ConvertLineRow::EndSequence(_length) => {
                sequences.push(std::mem::take(&mut current_sequence));
                current_base = 0;
            }
        }
    }

    // sequence[i] is assigned to the i-th local function (sorted by index);
    // refuse mismatches so we never silently assign wrong source locations.
    if sequences.len() != per_func_new.len() {
        return Err(Error::DwarfError(format!(
            ".debug_line sequence/function count mismatch ({} vs {})",
            sequences.len(),
            per_func_new.len()
        )));
    }

    // `convert` already translated read FileIds into the write program's FileId
    // space, so we copy `row.file` verbatim and don't need the file mapping.
    let (mut new_program, _file_mapping) = convert.program();

    // `per_func_new` is a BTreeMap, so iteration order is function-index
    // sorted; sequence i in the input line program corresponds to the i-th
    // local function in that order.
    for (seq_idx, func_idx) in per_func_new.keys().enumerate() {
        let Some(orig_dbg) = debug.per_func.get(func_idx) else {
            // Should not happen if parse-side capture is complete.
            continue;
        };
        let Some(orig_pcs) = orig_per_instr_pcs.get(func_idx) else {
            continue;
        };
        let new_maps = per_func_new.get(func_idx).unwrap();

        // Build a PC-sorted `(orig_pc, &row)` list for this function's input
        // sequence. Rows define implicit ranges (each row's source is in
        // effect until the next row's address), so the right lookup is
        // "find the row whose PC is the largest ≤ query PC" — same semantics
        // as `lookup_src_at` in the test helpers. Exact-key match would miss
        // rows that sit mid-instruction or at past-end source markers (rustc
        // emits both).
        let Some(input_seq) = sequences.get(seq_idx) else {
            // Input had no sequence for this function: leave it without
            // line-program coverage.
            continue;
        };
        let orig_first_abs = orig_dbg.dwarf_addr_base + orig_dbg.first_instr_dwarf_offset;
        let mut rows_by_orig_pc: Vec<(usize, &write::LineRow)> = input_seq
            .iter()
            .filter_map(|cr| {
                let addr = cr.address as usize;
                if addr < orig_first_abs {
                    return None;
                }
                Some((addr - orig_first_abs, &cr.row))
            })
            .collect();
        rows_by_orig_pc.sort_by_key(|&(pc, _)| pc);

        // Sequence base = new module-cumulative address of this function's
        // first body byte. Row `address_offset` is then the in-function offset
        // (`first_instr_dwarf_offset + new_pc`); end_sequence takes the
        // body length, yielding an absolute end of `dwarf_addr_base + body_total_size`.
        new_program.begin_sequence(Some(Address::Constant(new_maps.dwarf_addr_base as u64)));
        for (emit_idx, &new_pc) in new_maps.pcs.iter().enumerate() {
            let anchor = new_maps.anchors[emit_idx];
            let Some(&orig_pc) = orig_pcs.get(anchor) else {
                continue;
            };
            // Largest `(p, _)` with `p <= orig_pc`. None means no row covers
            // this PC (the function's prologue, before any row sets a
            // location) — skip the emit position rather than fabricate one.
            let after = rows_by_orig_pc.partition_point(|&(p, _)| p <= orig_pc);
            if after == 0 {
                continue;
            }
            let src_row = rows_by_orig_pc[after - 1].1;
            let new_addr_offset = (new_maps.first_instr_dwarf_offset + new_pc) as u64;
            let row = new_program.row();
            row.address_offset = new_addr_offset;
            row.file = src_row.file;
            row.line = src_row.line;
            row.column = src_row.column;
            row.is_statement = src_row.is_statement;
            row.basic_block = src_row.basic_block;
            row.prologue_end = src_row.prologue_end;
            row.epilogue_begin = src_row.epilogue_begin;
            row.discriminator = src_row.discriminator;
            new_program.generate_row();
        }
        new_program.end_sequence(new_maps.body_total_size as u64);
    }

    // Use `dwarf_write`'s string tables — the program's row strings were
    // registered into them via `convert`, and gimli enforces matching BaseIds.
    let mut writer = DebugLine::from(EndianVec::new(endian));
    let encoding = new_program.encoding();
    new_program
        .write(
            &mut writer,
            encoding,
            &mut dwarf_write.line_strings,
            &mut dwarf_write.strings,
        )
        .map_err(|e| Error::DwarfError(format!("writing line program: {e}")))?;

    Ok(writer.0.into_vec())
}

/// Translate a per-function orig DWARF address to its new equivalent. Handles
/// these zones inside the function body:
///
/// - **End-of-function** (`addr >= body_total_size_orig`): clamp to
///   `body_total_size_new` so `high_pc` / sentinel addresses land at the new
///   one-past-end.
/// - **Function start** (`addr == 0`): identity. The size-LEB byte sits at
///   address 0 in both orig and new.
/// - **Body-content start** (`addr == size_leb_len_orig`): map to
///   `size_leb_len_new`. wasm-tools' `subprogram` `low_pc` typically lands
///   here.
/// - **First instruction** (`addr == first_instr_dwarf_offset_orig`): map to
///   `first_instr_dwarf_offset_new`.
/// - **Header zone, other addresses** (size-LEB body / locals interior):
///   DWARF rarely names these. We pass through identity and `debug_assert!`
///   so a regression surfaces during development.
/// - **Instruction zone**: find the orig op whose range contains `addr` via
///   `partition_point` on the sorted `orig_pcs`, then look up the orig op's
///   own emit position (so `low_pc` lands on the orig op rather than a
///   leading before-injection). Preserve any byte offset inside the op.
fn translate_func_addr(
    orig_addr: u64,
    orig_dbg: &OrigFuncDebugData,
    new_maps: &PerFuncEncodeMaps<'_>,
    orig_pcs: &[usize],
) -> Option<u64> {
    // `orig_pcs` sortedness is the load-bearing assumption for the
    // `partition_point` below. We validate once per route entry when the
    // table is built (in `rewrite_other_dwarf_sections`) rather than per
    // address, since this function runs once per DWARF address — which can
    // be in the millions for instrumented modules in debug builds.

    let addr = orig_addr as usize;

    if addr >= orig_dbg.body_total_size {
        return Some(new_maps.body_total_size as u64);
    }
    if addr == 0 {
        return Some(0);
    }
    if addr == orig_dbg.size_leb_len {
        return Some(new_maps.size_leb_len as u64);
    }
    if addr == orig_dbg.first_instr_dwarf_offset {
        return Some(new_maps.first_instr_dwarf_offset as u64);
    }
    if addr < orig_dbg.first_instr_dwarf_offset {
        debug_assert!(
            false,
            "DWARF addr in function header but not at a known boundary: {addr}"
        );
        return Some(orig_addr);
    }

    let pc_in_func = addr - orig_dbg.first_instr_dwarf_offset;
    // `orig_pcs` is sorted ascending; `partition_point` finds the first index
    // whose PC exceeds `pc_in_func`, so the preceding index is the orig op
    // containing the address.
    let after = orig_pcs.partition_point(|&p| p <= pc_in_func);
    if after == 0 {
        // Shouldn't happen — we already handled addr <= first_instr above.
        return None;
    }
    let orig_idx = after - 1;
    let emit_idx = new_maps.self_emit_for_orig[orig_idx];
    if emit_idx == usize::MAX {
        // Orig op was dropped during encode (e.g., a future deletion API).
        // Surface as InvalidAddress through the closure rather than panicking.
        return None;
    }
    // `.get()` rather than direct index: defends against a future encode
    // bug that populates `self_emit_for_orig[i]` with an in-range-but-stale
    // emit position (e.g., the orig op moved across a deletion). A None
    // here surfaces as InvalidAddress, not a release-mode panic.
    let &new_pc = new_maps.pcs.get(emit_idx)?;
    let offset_in_op = pc_in_func - orig_pcs[orig_idx];
    Some((new_maps.first_instr_dwarf_offset + new_pc + offset_in_op) as u64)
}

/// Rewrite the PC-bearing DWARF sections other than `.debug_line` (handled by
/// `rewrite_debug_line`). Uses `gimli::write::Dwarf::convert` with a manual
/// per-DIE attribute walk so `DW_AT_low_pc` / `DW_AT_high_pc` stored as
/// constants (wasm-tools' convention) — which gimli's auto-conversion would
/// pass through verbatim — get translated alongside `DW_FORM_addr` values.
///
/// Routes addresses across multiple local functions via the cumulative
/// `dwarf_addr_base` carried on the per-function maps.
pub(crate) fn rewrite_other_dwarf_sections(
    debug: &ModuleDebugData,
    per_func_new: &BTreeMap<u32, PerFuncEncodeMaps<'_>>,
    orig_per_instr_pcs: &BTreeMap<u32, &[usize]>,
) -> Result<HashMap<&'static str, Vec<u8>>, Error> {
    use gimli::{
        write::{self, Address, EndianVec, Sections},
        EndianSlice, LittleEndian, SectionId,
    };

    if !debug.sections().iter().any(|s| s.name == ".debug_info") {
        return Ok(HashMap::new());
    }

    let endian = LittleEndian;
    let empty = EndianSlice::new(&[], endian);
    let section_lookup = |name: &str| -> EndianSlice<'_, LittleEndian> {
        debug
            .sections()
            .iter()
            .find(|s| s.name == name)
            .map(|s| EndianSlice::new(s.data.as_ref(), endian))
            .unwrap_or(empty)
    };

    let dwarf_read = gimli::read::Dwarf::load(|id| -> Result<_, gimli::Error> {
        Ok(match id {
            SectionId::DebugInfo => section_lookup(".debug_info"),
            SectionId::DebugAbbrev => section_lookup(".debug_abbrev"),
            SectionId::DebugLine => section_lookup(".debug_line"),
            SectionId::DebugStr => section_lookup(".debug_str"),
            SectionId::DebugLineStr => section_lookup(".debug_line_str"),
            SectionId::DebugStrOffsets => section_lookup(".debug_str_offsets"),
            SectionId::DebugLoc => section_lookup(".debug_loc"),
            SectionId::DebugLocLists => section_lookup(".debug_loclists"),
            SectionId::DebugRanges => section_lookup(".debug_ranges"),
            SectionId::DebugRngLists => section_lookup(".debug_rnglists"),
            SectionId::DebugAranges => section_lookup(".debug_aranges"),
            SectionId::DebugFrame => section_lookup(".debug_frame"),
            _ => empty,
        })
    })
    .map_err(|e| Error::DwarfError(format!("loading DWARF: {e}")))?;

    // Build a routing table sorted by orig `dwarf_addr_base`. Each entry pairs
    // the orig/new per-function metadata with the orig per-instruction PCs the
    // translator needs. Sorting once up-front lets the closure use
    // `partition_point` for O(log n) routing per address.
    let mut route: Vec<(&OrigFuncDebugData, &PerFuncEncodeMaps<'_>, &[usize])> = per_func_new
        .iter()
        .filter_map(|(idx, new_maps)| {
            let orig_dbg = debug.per_func.get(idx)?;
            let orig_pcs = orig_per_instr_pcs.get(idx)?;
            Some((orig_dbg, new_maps, *orig_pcs))
        })
        .collect();
    route.sort_unstable_by_key(|(orig_dbg, _, _)| orig_dbg.dwarf_addr_base);
    // Per-function invariant the translator hot path assumes: each function's
    // `orig_pcs` is sorted ascending. Validate once here rather than on every
    // call to `translate_func_addr`.
    debug_assert!(
        route
            .iter()
            .all(|(_, _, pcs)| pcs.windows(2).all(|w| w[0] <= w[1])),
        "orig_pcs must be sorted ascending per function (partition_point assumption)",
    );

    let translator = move |orig_addr: u64| -> Option<Address> {
        if route.is_empty() {
            return Some(Address::Constant(orig_addr));
        }
        // Find the last function whose `dwarf_addr_base <= orig_addr`. That
        // covers the in-body case and routes one-past-end addresses to the
        // function they semantically extend from (e.g., CU.high_pc lands on
        // the last function's body end). Also relies on functions being
        // emitted contiguously in code-section order — any future encode
        // change that inserts padding between bodies would break the
        // "one-past-end of k-1 == start of k" coincidence the boundary
        // case rides on.
        let after = route.partition_point(|(d, _, _)| (d.dwarf_addr_base as u64) <= orig_addr);
        if after == 0 {
            // Address below the first function's base — outside any function
            // we know how to translate. wasm-tools' convention puts the first
            // function at base 0 so this branch never fires for that input,
            // but other emitters (e.g., DWARF with a leading thunk / header
            // region) may put non-instruction addresses here. Pass through
            // unchanged rather than drop the DIE; the alternative is silent
            // attribute loss on legal-but-unconventional inputs.
            return Some(Address::Constant(orig_addr));
        }
        let (orig_dbg, new_maps, orig_pcs) = route[after - 1];
        let per_func_addr = orig_addr - orig_dbg.dwarf_addr_base as u64;
        let per_func_new = translate_func_addr(per_func_addr, orig_dbg, new_maps, orig_pcs)?;
        Some(Address::Constant(new_maps.dwarf_addr_base as u64 + per_func_new))
    };

    let mut dwarf_write = write::Dwarf::default();
    convert_units_with_low_high_pc(&mut dwarf_write, &dwarf_read, &translator)
        .map_err(|e| Error::DwarfError(format!("converting DWARF: {e}")))?;

    let mut sections = Sections::new(EndianVec::new(endian));
    dwarf_write
        .write(&mut sections)
        .map_err(|e| Error::DwarfError(format!("writing DWARF: {e}")))?;

    let mut out: HashMap<&'static str, Vec<u8>> = HashMap::new();
    let mut take = |name: &'static str, bytes: Vec<u8>| {
        if !bytes.is_empty() {
            out.insert(name, bytes);
        }
    };
    // `gimli::write::Sections` does not include `.debug_aranges` or
    // `.debug_str_offsets`: gimli doesn't generate those, so they currently
    // pass through verbatim and may go stale after instrumentation. Worth
    // a follow-up for inputs that carry an aranges table.
    take(".debug_info", sections.debug_info.0.into_vec());
    take(".debug_abbrev", sections.debug_abbrev.0.into_vec());
    take(".debug_str", sections.debug_str.0.into_vec());
    take(".debug_line_str", sections.debug_line_str.0.into_vec());
    take(".debug_loc", sections.debug_loc.0.into_vec());
    take(".debug_loclists", sections.debug_loclists.0.into_vec());
    take(".debug_ranges", sections.debug_ranges.0.into_vec());
    take(".debug_rnglists", sections.debug_rnglists.0.into_vec());
    take(".debug_frame", sections.debug_frame.0.into_vec());
    Ok(out)
}

/// Drive `gimli::write::Dwarf::convert` per-unit, walking each DIE manually so
/// we can intercept `DW_AT_low_pc` / `DW_AT_high_pc` stored as constants and
/// translate them. Per gimli's own contract, the default `convert_attribute_value`
/// passes `Data*` / `Udata` through verbatim — which would leave function
/// length attributes stale after instrumentation. We sidestep that here.
///
/// `.debug_line` writing is left to the dedicated step-5 rewriter: gimli's
/// auto-converted line program is still attached to each unit via
/// `set_line_program`, but `.debug_line` bytes for the output module come
/// from `rewrite_debug_line`. The caller writes our line bytes after this
/// function's output.
fn convert_units_with_low_high_pc(
    dwarf_write: &mut gimli::write::Dwarf,
    dwarf_read: &gimli::read::Dwarf<gimli::EndianSlice<'_, gimli::LittleEndian>>,
    translator: &dyn Fn(u64) -> Option<gimli::write::Address>,
) -> gimli::write::ConvertResult<()> {
    let mut conv_section = dwarf_write.convert(dwarf_read)?;
    while let Some((mut conv_unit, root_entry)) = conv_section.read_unit()? {
        if let Some(convert_program) = conv_unit.read_line_program(None, None)? {
            let (program, files) = convert_program.convert(translator)?;
            conv_unit.set_line_program(program, files);
        }

        let root_id = conv_unit.unit.root();
        convert_die(&mut conv_unit, root_id, &root_entry, translator)?;

        let mut entry = root_entry;
        while let Some(id_opt) = conv_unit.read_entry(&mut entry)? {
            if id_opt.is_none() {
                continue;
            }
            let id = conv_unit.add_entry(id_opt, &entry);
            convert_die(&mut conv_unit, id, &entry, translator)?;
        }
    }
    Ok(())
}

/// Convert one DIE's attributes, intercepting `DW_AT_low_pc` (any form) and
/// `DW_AT_high_pc` (`Data*`/`Udata` = offset length per the DWARF spec) so
/// instrumented modules get the right addresses. Other attributes go through
/// `convert_attribute_value` unchanged.
///
/// One pre-scan finds `low_pc` and translates it once; the main loop reuses
/// the cached translation when writing both `low_pc` and `high_pc`. Mirrors
/// gimli's own skip of `DW_AT_GNU_locviews` (an unsupported GNU extension).
fn convert_die<R: gimli::read::Reader<Offset = usize>>(
    conv_unit: &mut gimli::write::ConvertUnit<'_, R>,
    id: gimli::write::UnitEntryId,
    entry: &gimli::write::ConvertUnitEntry<'_, R>,
    translator: &dyn Fn(u64) -> Option<gimli::write::Address>,
) -> gimli::write::ConvertResult<()> {
    use gimli::{constants::*, write::ConvertError};

    // Pre-scan for low_pc and translate it once. DWARF doesn't strictly order
    // low_pc before high_pc, so this can't be folded into the main loop
    // without buffering.
    let orig_low_pc: Option<u64> = entry
        .attrs
        .iter()
        .find(|attr| attr.name() == DW_AT_low_pc)
        .and_then(|attr| read_pc_uint(&attr.value()));
    let new_low_pc_abs: Option<u64> = match orig_low_pc {
        Some(v) => match translator(v) {
            Some(gimli::write::Address::Constant(a)) => Some(a),
            Some(_) | None => return Err(ConvertError::InvalidAddress),
        },
        None => None,
    };

    for attr in &entry.attrs {
        let name = attr.name();
        if name == DW_AT_GNU_locviews {
            continue;
        }
        let value = if name == DW_AT_low_pc {
            write_low_pc_attr(
                attr,
                new_low_pc_abs.expect("we set it from this attr above"),
            )?
        } else if name == DW_AT_high_pc {
            translate_high_pc_attr(attr, translator, orig_low_pc, new_low_pc_abs)?
        } else {
            conv_unit.convert_attribute_value(entry.read_unit, attr, translator)?
        };
        conv_unit.unit.get_mut(id).set(name, value);
    }
    Ok(())
}

/// Decode a `DW_AT_low_pc` / `DW_AT_high_pc` raw value into the absolute u64
/// the rewriter operates on. Used by both passes through `convert_die` so the
/// form recognition can't drift between them.
fn read_pc_uint<R: gimli::read::Reader<Offset = usize>>(
    value: &gimli::read::AttributeValue<R>,
) -> Option<u64> {
    use gimli::read::AttributeValue as RA;
    match *value {
        RA::Addr(a) => Some(a),
        RA::Data1(d) => Some(d as u64),
        RA::Data2(d) => Some(d as u64),
        RA::Data4(d) => Some(d as u64),
        RA::Data8(d) => Some(d),
        RA::Udata(d) => Some(d),
        _ => None,
    }
}

/// Write a translated `low_pc` value back in the same form it was read in.
/// Unexpected forms (e.g. `Sdata`, string refs) are an error rather than a
/// silent zero — the wast convention only uses `Addr`/`Data4`.
fn write_low_pc_attr<R: gimli::read::Reader<Offset = usize>>(
    attr: &gimli::read::Attribute<R>,
    new_abs: u64,
) -> gimli::write::ConvertResult<gimli::write::AttributeValue> {
    use gimli::{read::AttributeValue as RA, write::AttributeValue as WA, write::ConvertError};
    Ok(match attr.value() {
        RA::Addr(_) => WA::Address(gimli::write::Address::Constant(new_abs)),
        RA::Data1(_) => WA::Data1(u8::try_from(new_abs).map_err(|_| ConvertError::InvalidAddress)?),
        RA::Data2(_) => {
            WA::Data2(u16::try_from(new_abs).map_err(|_| ConvertError::InvalidAddress)?)
        }
        RA::Data4(_) => {
            WA::Data4(u32::try_from(new_abs).map_err(|_| ConvertError::InvalidAddress)?)
        }
        RA::Data8(_) => WA::Data8(new_abs),
        RA::Udata(_) => WA::Udata(new_abs),
        _ => return Err(ConvertError::InvalidAttributeValue),
    })
}

fn translate_high_pc_attr<R: gimli::read::Reader<Offset = usize>>(
    attr: &gimli::read::Attribute<R>,
    translator: &dyn Fn(u64) -> Option<gimli::write::Address>,
    orig_low_pc: Option<u64>,
    new_low_pc_abs: Option<u64>,
) -> gimli::write::ConvertResult<gimli::write::AttributeValue> {
    use gimli::{read::AttributeValue as RA, write::AttributeValue as WA, write::ConvertError};

    // For Addr form, high_pc is an absolute address: translate directly.
    if let RA::Addr(a) = attr.value() {
        return match translator(a) {
            Some(addr) => Ok(WA::Address(addr)),
            None => Err(ConvertError::InvalidAddress),
        };
    }

    // For Data*/Udata forms, high_pc is a length (offset from low_pc). Recover
    // the orig absolute via orig_low + length, translate it, subtract new low.
    let length = match attr.value() {
        RA::Data1(d) => d as u64,
        RA::Data2(d) => d as u64,
        RA::Data4(d) => d as u64,
        RA::Data8(d) => d,
        RA::Udata(d) => d,
        _ => return Err(ConvertError::InvalidAttributeValue),
    };
    let (Some(orig_low), Some(new_low)) = (orig_low_pc, new_low_pc_abs) else {
        return Err(ConvertError::InvalidAttributeValue);
    };
    let orig_high_abs = orig_low
        .checked_add(length)
        .ok_or(ConvertError::InvalidAttributeValue)?;
    let new_high_abs = match translator(orig_high_abs) {
        Some(gimli::write::Address::Constant(a)) => a,
        _ => return Err(ConvertError::InvalidAddress),
    };
    let new_length = new_high_abs
        .checked_sub(new_low)
        .ok_or(ConvertError::InvalidAttributeValue)?;
    Ok(match attr.value() {
        RA::Data1(_) => {
            WA::Data1(u8::try_from(new_length).map_err(|_| ConvertError::InvalidAttributeValue)?)
        }
        RA::Data2(_) => {
            WA::Data2(u16::try_from(new_length).map_err(|_| ConvertError::InvalidAttributeValue)?)
        }
        RA::Data4(_) => {
            WA::Data4(u32::try_from(new_length).map_err(|_| ConvertError::InvalidAttributeValue)?)
        }
        RA::Data8(_) => WA::Data8(new_length),
        RA::Udata(_) => WA::Udata(new_length),
        _ => unreachable!("filtered above"),
    })
}
