name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merge == true && github.event.pull_request.head == 'automated_release' && github.event.pull_request.base == 'main'
    steps:
      - name: Publish Update
        run: cargo publish
