name: Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merge == true && github.event.pull_request.head == 'automated_release'
    steps:
      - name: cargo login
        run: cargo login ${{ secrets.ORCA_API_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish Update
        run: cargo publish
