name: Release

on:
  push:
    tags:
      - "release-v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check Code style quickly by running `rustfmt` over all code
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  build_and_test:
    name: Build project and run all unit AND integration tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-tools
        run: |
          cargo install wasm-tools
      - name: Build
        run: |
          cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose

  release:
    name: Release a new version of orca
    needs: [ rustfmt, build_and_test ]
    runs-on: ubuntu-latest
    permissions:
      # Gives write permisison to commit toml changes
      contents: write
      pull-requests: write

    steps:
      - name: cargo login
        run: cargo login ${{ secrets.ORCA_API_TOKEN }}

      - name: Uninstall Existing cargo-bump
        run: cargo uninstall cargo-bump || true

      - uses: actions/checkout@v4
      - name: Bump Version
        id: bump
        uses: tj-actions/cargo-bump@v3
        with:
          release_type: 'patch'

      - name: Commit updated toml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version Bump
          file_pattern: 'Cargo.toml'
          branch: automated-release
          create_branch: 'true'