name: Release Patch

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check Code style quickly by running `rustfmt` over all code
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  build_and_test:
    name: Build project and run all unit AND integration tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install wasm-tools
        run: |
          cargo install wasm-tools
      - name: Build
        run: |
          cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose

  release:
    name: Release a new version of orca
    needs: [ rustfmt, build_and_test ]
    runs-on: ubuntu-latest
    permissions:
      # Gives write permission to commit toml changes
      contents: write
      pull-requests: write

    steps:
      - name: cargo login
        run: cargo login ${{ secrets.ORCA_API_TOKEN }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Version
        id: bump
        uses: tj-actions/cargo-bump@v3
        with:
          release_type: 'patch'

      - name: Raise PR with changes
        uses: peter-evans/create-pull-request@v7
        with:
          branch: 'release/${{ steps.bump.outputs.new_version }}'