name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check Code style quickly by running `rustfmt` over all code
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: rustup component add rustfmt
    - run: cargo fmt --all -- --check

  build_and_test:
    name: Build project and run all unit AND integration tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-tools
      run: |
        cargo install wasm-tools
    - name: Build
      run: |
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  fuzz:
    name: Fuzzing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        rustup update nightly
        cargo install cargo-fuzz
        cargo +nightly fuzz build

    - name: Fuzz
      run: |
        cargo +nightly fuzz run module -- -max_total_time=180
        cargo +nightly fuzz run component -- -max_total_time=180