name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Check Code style quickly by running `rustfmt` over all code
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: rustup install stable
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-features --all-targets

  build_and_test:
    name: Build project and run all unit AND integration tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-tools
      run: |
        cargo install wasm-tools --version 1.235.0
    - name: Build
      run: |
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
